name: Ubuntu pbuilder CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run:
        sudo apt-get install -y autopoint debian-archive-keyring dpkg gettext builder
    - name: pbulder_prepare
      run: |
        export BASETGZ="$HOME/pbuilder-bases/debian-sid-$TARGET_ARCH.tgz"
        MIRROR=http://cdn-fastly.deb.debian.org/debian
        KEYRING=/usr/share/keyrings/debian-archive-keyring.gpg
        if [ ! -e "$BASETGZ.stamp" ]; then
          mkdir -p "$HOME/pbuilder-bases"
          sudo pbuilder --create --basetgz "$BASETGZ" --mirror $MIRROR \
            --distribution sid --architecture $TARGET_ARCH \
            --debootstrapopts --variant=buildd \
            --debootstrapopts --keyring=$KEYRING \
            --debootstrapopts --include=perl
          touch "$BASETGZ.stamp"
        else
          sudo pbuilder --update --basetgz "$BASETGZ"
        fi
    - name: src_archive
      run:
        git archive --format tgz -o ../zbar_$(more configure.ac |grep AC_INIT|perl -ne 'print $1 if /(\d+.\d+)/').orig.tar.gz HEAD

    - name: build
      run: |
        DIR="$PWD"
        cd ..
        dpkg-source -b "$DIR"
        env -i CC="$CC" CXX="$CXX" sudo pbuilder --build --debbuildopts --jobs=auto --basetgz "$BASETGZ" *.dsc
